# Generated by Django 4.0.4 on 2022-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='experince',
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
    ]
