# Generated by Django 4.0.4 on 2022-06-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job')},
        ),
    ]
