# Generated by Django 4.0.4 on 2022-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(null=True, upload_to='companyprofile'),
        ),
    ]
